name: "Setup Sloth"
description: "Setup Sloth for GitHub Actions"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl https://static.tipee.dev/releases/sloth/latest/sloth-linux-amd64 | sudo tee /usr/local/bin/sloth >/dev/null
        sudo chmod +x /usr/local/bin/sloth
