name: "Setup Sloth"
description: "Setup Sloth for GitHub Actions"
inputs:
  channel:
    description: The Sloth build channel to use
    default: 'latest'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl "https://static.tipee.dev/releases/sloth/$SLOTH_CHANNEL/sloth-linux-amd64" | sudo tee /usr/local/bin/sloth >/dev/null
        sudo chmod +x /usr/local/bin/sloth

        token="$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=//sloth.tipee.dev")"
        if [ ! -z "$token" ]; then
          echo "SLOTH_IDENTITY=github::$token" >> "$GITHUB_ENV"
        fi
      env:
        SLOTH_CHANNEL: ${{ inputs.channel }}
